version: "3.9"
services:
  db:
    image: postgres:17.4-alpine
    container_name: med_db
    environment:
      POSTGRES_DB: medschedule
      POSTGRES_USER: meds
      POSTGRES_PASSWORD: meds
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meds -d medschedule"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: med_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/medschedule
      DB_USER: meds
      DB_PASSWORD: meds
      JWT_SECRET: "please-change-this-to-a-very-long-random-secret"
      SPRING_PROFILES_ACTIVE: ""
    ports:
      - "8080:8080"

volumes:
  dbdata:
